### ISSUE TITLE
Difficulty with picking up comments

### ISSUE THREAD

**Issue by ghost** [orefalo/staruml3-graphql#1]
So I've ensured that IDL Comments are turned on in preferences, and I've added comments in the 'documentation' for each element as well as the type but both the preview and the resulting generated schema do not have any comments in them.

Am I doing something wrong?

![screen shot 2018-07-08 at 11 07 51 am](https://user-images.githubusercontent.com/1952419/42421187-32999f92-829f-11e8-8ea5-d6500283264d.png)

**Comment by orefalo** [comment]
Bug, will fix soon

**Comment by orefalo** [comment]
It's fixed, will be available once StarUML update their references. or you may download release from https://github.com/orefalo/staruml3-graphql/releases/tag/3.0.1

It's now available, plz reopen if you still have the issue
